export const warmUpRoutines = [
  {
    id: 'quick-sls',
    name: 'Quick SLS Warm-Up',
    duration: '8 min',
    level: 'All Levels',
    totalSeconds: 480,
    steps: [
      { name: 'Lip Trills — 5-Tone Scale', duration: '2 min', seconds: 120, description: 'Bubble lips on 1-2-3-4-5-4-3-2-1, ascending by half steps. Lightens cord compression — SLS foundation.' },
      { name: 'Tongue Trills — 5-Tone Scale', duration: '1.5 min', seconds: 90, description: 'Roll tongue (Spanish R), isolates breath from tongue tension. Use "BRR" if can\'t trill.' },
      { name: '"Mum" — 1.5 Octave Scale', duration: '2 min', seconds: 120, description: 'M creates cord closure. Speech-level effort — calling across room, not yelling.' },
      { name: '"Nay Nay" — Bratty Edge', duration: '1.5 min', seconds: 90, description: 'Exaggerated bratty NAY (cartoon witch) on 5-tone. Engages pharyngeal resonance for mix voice.' },
      { name: 'Gentle Sirens', duration: '1 min', seconds: 60, description: 'Slide lowest to highest on "OOH". Let voice flip — reveals bridges.' },
    ],
  },
  {
    id: 'full-sls',
    name: 'Full SLS Session',
    duration: '25 min',
    level: 'Intermediate',
    totalSeconds: 1500,
    steps: [
      { name: 'Diaphragmatic Breathing Reset', duration: '2 min', seconds: 120, description: 'Nose breathing 4-hold-4-exhale 8 on SSS. Establishes appoggio.' },
      { name: 'Lip Trills Full Range', duration: '3 min', seconds: 180, description: 'Through first bridge, mix, head voice and back. If pushing = too loud.' },
      { name: 'Tongue Trills Full Range', duration: '2 min', seconds: 120, description: 'Consistent airflow, notice shift points.' },
      { name: '"Mum" Chest to Mix', duration: '3 min', seconds: 180, description: "Don't increase volume ascending. Let resonance shift to mask." },
      { name: '"Gug" Cord Closure', duration: '2 min', seconds: 120, description: 'Hard G forces clean closure. Open throat + firm cords.' },
      { name: '"Nay" Pharyngeal Resonance', duration: '3 min', seconds: 180, description: 'Bratty NAY on 1.5-octave. Thyroid tilt for mix voice. Rock belting gold.' },
      { name: '"Noh" Vowel Modification', duration: '2 min', seconds: 120, description: 'NOH on arpeggios. OH narrows to UH ascending. Acoustic physics.' },
      { name: '"Gee" Head Voice', duration: '2 min', seconds: 120, description: 'Light GEE thins cords. Build bridge between chest and head.' },
      { name: 'Phrase Work', duration: '3 min', seconds: 180, description: 'Phoenix song phrase on MUM then NAY then lyrics.' },
      { name: 'Cool-Down Sirens', duration: '3 min', seconds: 180, description: 'Descending OOH sirens getting quieter.' },
    ],
  },
  {
    id: 'rock-prep',
    name: 'Rock Performance Prep',
    duration: '15 min',
    level: 'Advanced',
    totalSeconds: 900,
    steps: [
      { name: 'Breath Power Staccato Bursts', duration: '2 min', seconds: 120, description: 'SH-SH-SH then HEY-HEY-HEY with diaphragm kicks.' },
      { name: 'Lip Trills With Grit', duration: '2 min', seconds: 120, description: 'Add vocal fry at onset for false fold texture.' },
      { name: '"Gug" Power Scales', duration: '2 min', seconds: 120, description: 'Moderate volume, clean closure. Power = efficiency not volume.' },
      { name: '"NAY" Belt Zone', duration: '3 min', seconds: 180, description: 'A3-E4 range, aggressive bratty. Thyroid tilt for sustainable belting.' },
      { name: '"WAH" Open Throat Power', duration: '2 min', seconds: 120, description: 'Like wah pedal on arpeggios. AH modified to UH above bridge.' },
      { name: 'Controlled Distortion', duration: '2 min', seconds: 120, description: 'Clean to gradual fry/rasp. False folds, NOT true cord abuse. Painless.' },
      { name: 'Song Run-Through', duration: '2 min', seconds: 120, description: 'Hardest chorus at 70%. Quiet first, then full energy.' },
    ],
  },
  {
    id: 'recovery',
    name: 'Vocal Recovery',
    duration: '10 min',
    level: 'All Levels',
    totalSeconds: 600,
    steps: [
      { name: 'Steam & Hydration', duration: '2 min', seconds: 120, description: 'Room temp water, avoid dairy/caffeine/alcohol.' },
      { name: 'Gentle Humming', duration: '2 min', seconds: 120, description: 'Volume 2/10, vibration in lips/nose not throat.' },
      { name: 'Straw Phonation SOVT', duration: '3 min', seconds: 180, description: 'Narrow straw sirens. Back-pressure cushions cords.' },
      { name: 'Soft Lip Trills Low Range', duration: '2 min', seconds: 120, description: 'Gentle massage only.' },
      { name: 'Silent Cool-Down', duration: '1 min', seconds: 60, description: 'Breathing only. Know when not to sing.' },
    ],
  },
];

export const slsExerciseCategories = [
  {
    name: 'Cord Closure',
    color: '#ec4899',
    exercises: [
      {
        name: '"Gug" — The Closure King',
        purpose: 'Forces clean cord closure with the hard G consonant while keeping the throat open.',
        pattern: '1-3-5-3-1 ascending/descending by half steps',
        howTo: 'Say "GUG" with a hard G on both ends. The G forces the cords to close firmly. Keep the throat open and relaxed — imagine swallowing a ping pong ball. Ascend by half steps through your bridges without increasing volume.',
        sethRiggsQuote: '"The G consonant forces the cords to come together. It\'s like a reset button for your voice."',
        commonMistakes: 'Pushing more air as you go higher. Tensing the jaw. Losing the hard G onset. Adding breath to the tone.',
        rockApplication: 'Essential for powerful, clean-onset rock phrases. Think of the attack on "God gave rock and roll to you" — that clean start needs cord closure.',
      },
      {
        name: '"Mum" — Connected Tone',
        purpose: 'Creates cord closure through the M consonant while maintaining connected, speech-level tone.',
        pattern: '1-2-3-4-5-4-3-2-1 ascending by half steps through full range',
        howTo: 'Say "MUM" as if calling someone across a room — not yelling, just projecting. The M brings the cords together naturally. Keep it conversational. As you ascend, the resonance should shift forward to the mask (behind the nose) without you forcing it.',
        sethRiggsQuote: '"Michael Jackson warmed up with MUM every single session. If it\'s good enough for MJ, it\'s good enough for you."',
        commonMistakes: 'Getting louder as you ascend. Pushing the tone from the throat. Losing the speech-level quality. Over-darkening the vowel.',
        rockApplication: 'Builds the connected tone needed for sustained rock phrases. Phoenix ballads need this legato quality.',
      },
    ],
  },
  {
    name: 'Mix Voice / Bridging',
    color: '#8b5cf6',
    exercises: [
      {
        name: '"Nay" — The Mix Finder',
        purpose: 'THE secret weapon for finding mix voice. The bratty, nasal quality engages the pharyngeal resonator.',
        pattern: '1-3-5-8-5-3-1 (1.5 octave) ascending by half steps',
        howTo: 'Say "NAY" like a bratty cartoon witch — exaggerated and nasally. This is NOT your performance voice. The twang and nasality tilt the thyroid cartilage, thinning the cords to find mix voice. Go through your bridge without flipping to falsetto. If it sounds ugly, you\'re doing it right.',
        sethRiggsQuote: '"If you can\'t do it ugly, you can\'t do it pretty. The NAY unlocks the door that your voice has been hiding behind."',
        commonMistakes: 'Not being bratty enough — commit to the ugly. Pulling chest voice too high instead of letting it thin. Flipping to falsetto. Being embarrassed by the sound.',
        rockApplication: 'This is how Bono, Steven Tyler, and Aretha Franklin find their high notes without strain. THE exercise for Phoenix high choruses.',
      },
      {
        name: '"Noh" — Vowel Transition',
        purpose: 'Teaches vowel modification through the passaggio (bridge). OH naturally narrows as you ascend.',
        pattern: '1-3-5-8 (arpeggio) ascending by half steps',
        howTo: 'Start with an open "NOH" sound. As you ascend through your bridge, allow the OH to naturally narrow toward UH. Don\'t fight it — this isn\'t cheating, it\'s acoustic physics. The resonance space changes as pitch rises, and the vowel must adapt.',
        sethRiggsQuote: '"Vowel modification isn\'t cheating — it\'s acoustic physics. A trumpet player changes their embouchure for high notes. You modify vowels."',
        commonMistakes: 'Forcing the same vowel shape across your entire range. Not allowing the natural narrowing. Over-modifying too early.',
        rockApplication: 'Essential for sustaining powerful high notes in rock without vocal fatigue. Think power ballad sustained notes.',
      },
      {
        name: 'Octave Repeat "Wee"',
        purpose: 'Creates instant chest-to-head voice connection through octave leaps.',
        pattern: '1-8-8-8-8 (octave jumps) ascending by half steps',
        howTo: 'Say "WEE" and jump from chest voice to head voice on the octave. Repeat the top note 4 times. The W helps with cord connection and the EE vowel keeps it light. Focus on the connection point between the registers.',
        sethRiggsQuote: '"The octave repeat teaches your voice that the bridge is a hallway, not a wall."',
        commonMistakes: 'Flipping to disconnected falsetto. Using too much force on the bottom note. Not keeping the EE vowel consistent.',
        rockApplication: 'Builds the athletic flexibility needed for rock vocal acrobatics and octave-jumping riffs.',
      },
    ],
  },
  {
    name: 'Range Extension',
    color: '#6366f1',
    exercises: [
      {
        name: 'Sirens — Full Range Glide',
        purpose: 'Maps your entire range and reveals where your bridges are. The non-negotiable before every gig.',
        pattern: 'Bottom to top to bottom on "OOH" — continuous glide',
        howTo: 'Start at your lowest comfortable note on "OOH" and slide continuously to your highest note, then back down. Don\'t skip — go through every note. Let your voice crack, flip, or break. Those break points are your bridges, and they\'re what you\'re training.',
        sethRiggsQuote: '"The siren is your vocal X-ray. It shows you exactly where the problems are — and where the gold is."',
        commonMistakes: 'Avoiding the break points. Pushing through bridges with force. Going too fast — take your time through the transitions.',
        rockApplication: 'Warm-up essential before every Phoenix rehearsal and gig. Reveals your range for the day.',
      },
      {
        name: '"Buh" — Low Range Expansion',
        purpose: 'Develops chest voice depth and power through descending scales.',
        pattern: '5-4-3-2-1 descending by half steps into lower range',
        howTo: 'Say "BUH" with a relaxed, open throat. Descend by half steps, going as low as comfortable. The B consonant provides light cord closure. Keep the tone resonant, not pressed or gravelly.',
        sethRiggsQuote: '"Your low range is the foundation of your house. Build it strong."',
        commonMistakes: 'Pressing or forcing the low notes. Adding unnecessary weight. Losing breath support as you descend.',
        rockApplication: 'Builds the powerful low register for rock verses and dynamic contrast.',
      },
      {
        name: '"Gee" — Head Voice Strengthening',
        purpose: 'Builds head voice strength with a light, ringing quality. Head voice is NOT falsetto.',
        pattern: '1-3-5-8-5-3-1 ascending into head voice',
        howTo: 'Say "GEE" lightly — think of a friendly greeting. The G provides clean onset, the EE thins the cords naturally for head voice. Keep it light and ringing, never airy or breathy. If it sounds like Mickey Mouse, that\'s actually closer than you think.',
        sethRiggsQuote: '"Head voice is not falsetto. Falsetto is disconnected air. Head voice is connected, thin, and powerful."',
        commonMistakes: 'Using falsetto instead of connected head voice. Making it too heavy. Losing the ring and brightness.',
        rockApplication: 'Critical for extended rock vocals and saving your voice during long sets. Head voice harmonies add texture to Phoenix arrangements.',
      },
    ],
  },
  {
    name: 'Resonance & Placement',
    color: '#f59e0b',
    exercises: [
      {
        name: 'Humming — Mask Resonance',
        purpose: 'Finds forward resonance placement without the interference of vowels or consonants.',
        pattern: '1-3-5-3-1 ascending by half steps, humming on M',
        howTo: 'Hum with lips together, teeth slightly apart. Feel the vibration in your lips, nose, and the "mask" area (behind the cheekbones). This is free volume — resonance gives you projection without pushing. The buzzy feeling means you\'re resonating efficiently.',
        sethRiggsQuote: '"Resonance is free volume. You don\'t pay for it with effort — physics gives it to you."',
        commonMistakes: 'Humming from the throat. Not feeling vibration in the mask. Tensing the jaw or tongue.',
        rockApplication: 'Mask resonance is how you cut through a loud band mix without destroying your voice. Essential for Phoenix gigs with Marshall stacks.',
      },
      {
        name: '"Nyah" — Twang & Projection',
        purpose: 'Maximizes forward resonance and cut-through with an exaggerated twangy quality.',
        pattern: '1-5-8-5-1 ascending by half steps',
        howTo: 'Say "NYAH" like a child taunting — nasally and forward. This extreme forward placement creates the "twang" that gives rock vocals their cutting power. It\'s the same mechanism that lets a baby\'s cry carry across a room without effort.',
        sethRiggsQuote: '"Twang isn\'t a style choice — it\'s a resonance strategy. Robert Plant uses it. So does Pavarotti."',
        commonMistakes: 'Not committing to the twang. Pulling the sound back into the throat. Confusing nasality with nasal congestion.',
        rockApplication: 'From Robert Plant to Chris Cornell, twang is what lets rock singers cut through Marshall stacks without shredding their voices. Phoenix needs this for outdoor gigs.',
      },
    ],
  },
];

export const breathingExercises = [
  {
    name: 'Belly Breathing Foundation',
    duration: '3 min',
    level: 'Beginner',
    steps: [
      'Lie down or stand with one hand on chest, one on belly.',
      'Breathe in through nose for 4 counts — only the belly hand should move.',
      'Hold for 2 counts.',
      'Exhale through mouth on SSS for 6 counts, belly drawing in.',
      'Repeat 8 times. If chest moves, slow down.',
    ],
    sethRiggsQuote: '"If your shoulders rise when you breathe, you\'re using only 30% of your lung capacity. Belly breathing uses it all."',
  },
  {
    name: 'Appoggio Technique',
    duration: '5 min',
    level: 'Intermediate',
    steps: [
      'Stand tall, shoulders relaxed, feet shoulder-width apart.',
      'Inhale through nose, expanding the belly AND the sides (like a barrel expanding).',
      'Begin to exhale on a steady SSS sound.',
      'As you exhale, resist the belly collapsing — maintain gentle outward pressure.',
      'This opposition creates steady, controlled airflow — the "lean" of appoggio.',
      'Practice sustaining SSS for 15, 20, then 30 seconds.',
    ],
    sethRiggsQuote: '"Appoggio means \'to lean\'. You lean against the breath, not push it. Think of a controlled tire deflation, not a balloon pop."',
  },
  {
    name: 'Staccato Diaphragm Kicks',
    duration: '3 min',
    level: 'Intermediate',
    steps: [
      'Place hands on lower ribs to feel the diaphragm.',
      'Sharp, short SH-SH-SH bursts — feel the belly kick inward on each one.',
      'Rest 10 seconds.',
      'Now do HEY-HEY-HEY with sharp diaphragm kicks.',
      'Increase speed gradually: slow, medium, fast.',
      'This builds the diaphragm strength for powerful vocal onsets.',
    ],
    sethRiggsQuote: '"The diaphragm is the engine. Staccato kicks are your engine warm-up."',
  },
  {
    name: 'Extended Exhale Training',
    duration: '4 min',
    level: 'All Levels',
    steps: [
      'Inhale through nose for 4 counts.',
      'Exhale on a steady SSS for 8 counts.',
      'Inhale for 4, exhale for 12.',
      'Inhale for 4, exhale for 16.',
      'Inhale for 4, exhale for 20.',
      'Goal: 30-second sustained SSS with even airflow.',
    ],
    sethRiggsQuote: '"Long phrases require long breath. Train your exhale and your phrasing will transform."',
  },
  {
    name: 'Breath Recovery Drill',
    duration: '3 min',
    level: 'Advanced',
    steps: [
      'Sing a phrase from a demanding Phoenix song.',
      'At the end of the phrase, take a quick "catch breath" — 1 second inhale through mouth.',
      'Immediately sing the next phrase.',
      'Practice the catch breath being silent and invisible.',
      'Goal: seamless phrase connections with no audible gasping.',
    ],
    sethRiggsQuote: '"The audience should never hear you breathe. Quick, silent breath management separates professionals from amateurs."',
  },
];

export const theoryLessons = [
  {
    title: 'What Is Speech Level Singing?',
    content: 'Speech Level Singing (SLS) is a vocal technique developed by Seth Riggs that trains singers to use the same comfortable, speech-level effort throughout their entire range. Instead of reaching, straining, or pushing for notes, SLS teaches the intrinsic muscles of the larynx to do the work while the extrinsic muscles (jaw, tongue, neck) stay relaxed. The larynx remains at a neutral, speech-level position — it doesn\'t rise for high notes or press down for low notes. Over 130 Grammy winners have trained with Seth Riggs using this method, including Michael Jackson, Stevie Wonder, Prince, and Natalie Cole.',
    keyPoints: [
      'Larynx stays neutral — no rising for high notes, no pressing for low notes',
      'Intrinsic muscles do the work, extrinsic muscles stay relaxed',
      'Same effort level as speaking — hence "Speech Level"',
      '130+ Grammy winners trained with Seth Riggs',
      'Works for ALL genres — pop, rock, R&B, opera, musical theater',
    ],
  },
  {
    title: 'Vocal Registers & Bridges',
    content: 'Every voice has distinct registers: chest voice (lower, speaking range), mix voice (middle, blended), and head voice (upper, lighter quality). Between these registers are "bridges" (also called passaggi) — transition points where the vocal cords must change their configuration. For most male voices, the first bridge is around E4-F#4. SLS exercises like NAY, MUM, and GUG are specifically designed to train smooth transitions through these bridges, eliminating the "crack" or "flip" that untrained voices experience.',
    keyPoints: [
      'Three main registers: Chest, Mix, and Head voice',
      'Male first bridge (passaggio): E4 to F#4',
      'NAY exercise finds mix voice through pharyngeal resonance',
      'MUM/GUG train cord closure through bridges',
      'The goal: seamless transitions, no flips or cracks',
      'Mix voice is NOT falsetto — it\'s connected, blended tone',
    ],
  },
  {
    title: 'Why SLS Works for Rock',
    content: 'Rock singing demands power, grit, and endurance — exactly what SLS delivers through efficiency rather than force. Resonance efficiency (mask placement, twang) gives you volume without pushing. False fold distortion provides rock texture without true cord abuse. The thyroid tilt mechanism (trained through NAY and bratty exercises) creates the "belt" sound sustainably. Steven Tyler, Bon Jovi, Bono, and Robert Plant all use SLS principles — they\'ve maintained their voices over decades of touring because their technique is efficient, not forceful.',
    keyPoints: [
      'Power through resonance efficiency, not force',
      'False fold distortion for rock grit — NOT true cord abuse',
      'Thyroid tilt mechanism for sustainable belting',
      'Steven Tyler, Bono, Robert Plant use SLS principles',
      'Vocal longevity through technique, not talent alone',
      'Mix voice is the rock singer\'s secret weapon',
    ],
  },
  {
    title: 'The Diaphragm Connection',
    content: 'The diaphragm is the engine of singing. SLS uses the "appoggio" technique — a balanced opposition between the inhalation muscles (which want to expand) and the exhalation muscles (which want to compress). This creates steady, minimal pressure airflow. Think of it like a car engine: you want smooth, consistent power delivery, not a series of explosions. The goal is minimal, steady pressure that lets the cords do their job. Too much air pressure forces the cords to resist, leading to strain, fatigue, and damage.',
    keyPoints: [
      'Appoggio: balanced opposition between inhale and exhale muscles',
      'Minimal, steady pressure — not maximum air volume',
      'Too much air = cord strain. Less is more.',
      'Diaphragmatic breathing uses full lung capacity',
      'The engine metaphor: smooth power, not explosions',
      'Breath management is 50% of great singing',
    ],
  },
  {
    title: 'Daily Practice Philosophy',
    content: 'Seth Riggs recommends 20-30 minutes of focused practice daily rather than long, exhausting sessions. Quality over quantity. The golden rule: if it hurts, stop. Discomfort means you\'re doing it wrong. Vocal cords are tiny muscles — they fatigue faster than your biceps. Build gradually: 15 minutes for beginners, working up to 30 minutes. Expect noticeable improvement in 6-12 weeks with consistent practice. Record yourself — your ears inside your head hear a different voice than the audience.',
    keyPoints: [
      '20-30 minutes daily — quality over quantity',
      'The Comfort Rule: if it hurts, STOP immediately',
      'Vocal cords are tiny — they fatigue faster than other muscles',
      'Record yourself regularly to track progress objectively',
      'Expect results in 6-12 weeks of consistent practice',
      'Never skip warm-ups before performing or heavy practice',
    ],
  },
  {
    title: "Seth Riggs' Legacy",
    content: 'Seth Riggs (1930-2022) was arguably the most influential voice teacher in modern music history. Over a 60+ year career, he coached more than 130 Grammy winners and pioneered the Speech Level Singing methodology. His students include Michael Jackson, Stevie Wonder, Prince, Ray Charles, Natalie Cole, Luther Vandross, and countless others. His book "Singing for the Stars" remains the definitive SLS text. The SLS method is now taught by certified instructors worldwide, and its principles have influenced virtually every modern vocal technique. His legacy lives on through the technique and the thousands of singers it has transformed.',
    keyPoints: [
      'Seth Riggs: 1930-2022, 60+ years of teaching',
      '130+ Grammy-winning students',
      'Famous students: Michael Jackson, Stevie Wonder, Prince',
      '"Singing for the Stars" — the definitive SLS textbook',
      'SLS certified instructors teach worldwide',
      'Influenced virtually every modern vocal technique',
    ],
  },
];

export const sethRiggsBio = {
  name: 'Seth Riggs',
  years: '1930-2022',
  title: 'Creator of Speech Level Singing',
  description: 'The most influential voice teacher in modern music history. Over 60 years of teaching, 130+ Grammy-winning students, and a methodology that revolutionized how the world teaches singing.',
  book: 'Singing for the Stars',
  famousStudents: ['Michael Jackson', 'Stevie Wonder', 'Prince', 'Ray Charles', 'Natalie Cole', 'Luther Vandross'],
};
